---
version: '2'

services:
  kissfs:
    image: kissfs
    container_name: kissfs
    ports:
      - ${HOST}:3000:3000
    volumes:
      - ${VOL}:/www
    networks:
      - web

networks:
  web:
    external:
      name: web
